/**
 * Audience-specific narrative: the "so what" line under each section and
 * the closing takeaway cards. Keyed by audience, then by section id.
 */

export const soWhat = {
  public:{map:'<b>Demand and infrastructure don\'t line up.</b> Indonesia, Pakistan and India have over 650 million Muslims between them, yet none is in the top ecosystem tier. Most halal goods they buy are produced elsewhere.',sectors:'<b>Food is the anchor, travel is the story.</b> Nearly $6 of every $10 goes on food, but Muslim-friendly travel is growing almost twice as fast, adding $175B by 2029.',growth:'<b>This is not a niche.</b> $2.6T in consumer spend is larger than the GDP of most countries. Islamic finance added roughly a trillion dollars in assets in a single year.',finance:'<b>Islamic finance is mostly banking, concentrated in a few places.</b> Saudi Arabia, Iran and Malaysia hold roughly 70% of all assets; ten countries hold about 95%.',countries:'<b>Non-Muslim-majority countries are major players.</b> The UK and Singapore rank in the top 15 ecosystems; Brazil, India and the US are among the largest halal food suppliers.',trade:'<b>The halal economy is a trading economy.</b> $421.5B of halal goods crossed borders into OIC countries in 2024, much of it from Brazil, India, Russia and the US.',business:'<b>Certification is the passport.</b> A product certified by a widely recognised body can travel; one that isn\'t, can\'t.'},
  investor:{map:'<b>Look for the gap.</b> The largest populations (Indonesia, Pakistan, Bangladesh, Nigeria) have weaker ecosystems than the Gulf and Malaysia — that is where certification, logistics and fintech infrastructure is under-supplied.',sectors:'<b>Travel has the highest rate; food the largest absolute gain.</b> Travel compounds at 11.2% to 2029; food adds over $500B in absolute terms. Media & recreation leads on deal count.',growth:'<b>Islamic finance is outgrowing consumer spend.</b> ~10% a year versus 6.5%, and Islamic funds are still sub-scale (most manage around $1M), leaving room for consolidation.',finance:'<b>Sukuk is the fastest-moving segment.</b> Issuance rose 25.6% in 2024 to about $254B; takaful grew 16.9% and remains under $31B globally — small, fragmented, digitising.',countries:'<b>Deal flow concentrates in Indonesia and the UAE</b> (~$1.6B and ~$1.5B). Islamic finance attracts the most capital; media & recreation the most transactions. Africa is the fastest-growing region.',trade:'<b>Import growth is the investable trend.</b> OIC imports are forecast to grow ~8% a year to $608B by 2028 — logistics, cold chain and certification services ride that curve regardless of which brand wins.',business:'<b>Certification and distribution are the moats.</b> Companies that already hold multi-market recognition trade at a premium to those that don\'t.'},
  policy:{map:'<b>Ecosystem scores reward coordination, not size.</b> Malaysia leads on certification, standards and finance rails. Countries with large Muslim populations but low scores are importing goods they could produce.',sectors:'<b>Certification is the lever.</b> Mutual-recognition agreements (Indonesia–UAE–Türkiye–Malaysia) cut compliance cost and widen market access across all six sectors at once.',growth:'<b>Trade is growing faster than consumption.</b> OIC halal imports are forecast to grow ~8% a year, versus 6.5% for consumer spend — import dependence widens unless domestic capacity grows.',finance:'<b>Standards fragmentation is the main brake.</b> Divergent Sharia rulings limit product portability. IFSB and AAOIFI harmonisation, and sovereign sukuk programmes, are the levers that have moved rankings.',countries:'<b>Fast movers show what works.</b> Pakistan entered the top ten and Senegal rose 18 places after targeted national strategies. The UK\'s 14th place shows non-Muslim-majority economies can compete on regulation and finance.',trade:'<b>A $421B import bill is also an industrial-policy target.</b> Food is ~70% of it. Domestic processing capacity, halal parks and export-grade certification are the standard playbook — Malaysia\'s halal parks attracted ~$2B from multinationals.',business:'<b>Recognition arrangements are the cheapest trade policy available.</b> A single mutual-recognition agreement can open several markets to domestic producers at once.'},
  business:{map:'<b>Pick your market by what you sell.</b> Volume is in Indonesia, Pakistan, Bangladesh and Nigeria. Premium and B2B is in the Gulf and Malaysia. The UK and Singapore are the easiest Western entry points.',sectors:'<b>Smaller sectors have less competition.</b> Cosmetics ($92B) and pharma ($112B) are a fraction of food but grow at 5.5–6.2% with fewer certified players.',growth:'<b>Values-driven buying is now structural.</b> Since 2023, alternative and local brands have held share gained during boycotts; halal certification increasingly signals ethics and quality to non-Muslim buyers too.',finance:'<b>Sharia-compliant financing is mainstream in the Gulf and Southeast Asia,</b> where Islamic banks are 20–75% of the market. Sukuk suits larger raises; takaful covers insurance.',countries:'<b>Producers outside the OIC win on supply.</b> Brazil, India and the US are top exporters into OIC markets. Certification turnaround (10–60+ days) and distributor onboarding (4–8 weeks) are the practical bottlenecks.',trade:'<b>Choose your certifier for the markets you want.</b> JAKIM, MUIS and GAC-accredited marks travel furthest; a UK or US-only mark may need re-certification for the Gulf or Indonesia.',business:'<b>Budget for certification lead time before launch dates.</b> 10–60+ days per certifier, and mandatory schemes (Indonesia) add product-category deadlines.'}
};
export const takeaways = {
  public:{title:'What this means for you',note:'A quick orientation to a market most people underestimate.',cards:[{tag:'Scale',h:'A quarter of humanity, spending $2.6 trillion a year',p:'Before counting the $6 trillion held in Islamic finance. Together the two are close to $9 trillion.'},{tag:'Growth',h:'Growing faster than the global economy',p:'Consumer spend is forecast at 6.5% a year to 2029, Islamic finance at around 10%. Both outpace typical global GDP growth.'},{tag:'Geography',h:'Produced in one place, consumed in another',p:'The biggest buyers are in Southeast Asia, South Asia and the Gulf. Some of the biggest suppliers — Brazil, India, the US — aren\'t Muslim-majority at all.'}]},
  investor:{title:'Where the opportunity sits',note:'Signals drawn from published industry research. Not investment advice.',cards:[{tag:'Highest growth',h:'Muslim-friendly travel: 11.2% a year to 2029',p:'From $249B to $424B. Hospitality, halal dining and pilgrimage-adjacent services, concentrated in the Gulf, Türkiye and Southeast Asia.'},{tag:'Capital markets',h:'Sukuk issuance up 25.6% in 2024',p:'About $254B issued, led by Saudi Arabia, Malaysia and Iran. Islamic funds remain sub-scale, which points to consolidation and platform plays.'},{tag:'Under-served',h:'Big populations, thin infrastructure',p:'Indonesia, Pakistan, Bangladesh and Nigeria have ~700M Muslims and comparatively weak certification, logistics and fintech rails. Indonesia is already the top deal destination.'}]},
  policy:{title:'Levers that have moved the needle',note:'What the rankings suggest about effective national strategy.',cards:[{tag:'Standards',h:'Certification and mutual recognition',p:'Malaysia\'s twelve-year lead rests on a unified certification regime. Multilateral recognition pacts reduce costs and widen access for exporters.'},{tag:'Trade balance',h:'OIC halal imports outgrowing consumption',p:'$421.5B in 2024, heading to $608B. Domestic production capacity in food, pharma and cosmetics is the gap most OIC economies are trying to close.'},{tag:'Finance',h:'Sovereign sukuk and harmonised rules',p:'Sovereign issuance anchors the sukuk market; harmonised Sharia governance lets products travel across borders. The UK\'s top-15 ranking shows this works outside Muslim-majority states.'}]},
  business:{title:'Practical entry points',note:'Where a business can realistically compete. Use the entry helper above for a shortlist.',cards:[{tag:'Product',h:'Pick a lane by sector size and competition',p:'Food is huge but crowded. Cosmetics and pharma are $90–110B markets growing 5.5–6.2% with far fewer certified players. Travel is the fastest-growing service category.'},{tag:'Market',h:'Match the market to your model',p:'Volume: Indonesia, Pakistan, Bangladesh, Nigeria. Premium and B2B: Gulf and Malaysia. Western entry: UK and Singapore, both top-15 ecosystems.'},{tag:'Operations',h:'Budget for certification lead time',p:'10 to 60+ days depending on certifier; distributor onboarding 4–8 weeks. Sharia-compliant financing is mainstream in the Gulf and Southeast Asia.'}]}
};
