/** Scrollytelling scripts for story mode. */

export const stories={
  gap:{kicker:'A short story in nine steps',title:'Where does a quarter of the world buy its food?',body:'Two billion people. Nine trillion dollars. And a map where the demand and the infrastructure sit in different places. Scroll to follow the story; the map changes as you go.',graphic:'map',steps:[
    {layer:'pop',hl:null,title:'Two billion people, spread across every continent',body:'Roughly a quarter of humanity is Muslim. The darker the country, the more Muslims live there. Notice where the colour pools: Southeast Asia, South Asia, the Middle East and a widening band across Africa.',stat:'worldMuslims',l:'Muslims worldwide, about 25% of the global population'},
    {layer:'pop',hl:['Indonesia','Pakistan','India','Bangladesh','Nigeria'],title:'Five countries hold almost half of them',body:'Indonesia, Pakistan, India, Bangladesh and Nigeria together are home to more than 900 million Muslims. This is where the demand is. None of the five is a Gulf state, and only Indonesia and Pakistan appear in the top ten halal ecosystems.',stat:'fiveCountries',l:'Muslims in these five countries alone',acts:[{label:'Show Indonesia on the map',act:'pin',args:['Indonesia']}]},
    {layer:'pop',hl:null,title:'Together they spend $2.6 trillion a year',body:'That is Muslim consumer spending across six halal sectors in 2024. Food takes nearly $6 of every $10. But the growth is elsewhere: Muslim-friendly travel is compounding at over 11% a year, almost twice the pace of food, and is forecast to reach $424 billion by 2029.',stat:'spend2024',l:'consumer spend, 2024. Forecast $3.56T by 2029'},
    {layer:'giei',hl:['Malaysia','United Arab Emirates','Saudi Arabia','Bahrain','Kuwait','Qatar','Jordan'],title:'But the infrastructure sits somewhere else',body:'Switch the lens to ecosystem strength — certification, regulation, finance, innovation — and the map re-centres on Malaysia and the Gulf. The Global Islamic Economy Indicator measures how well a country is set up to serve halal demand, not how much demand it has.',stat:'malaysiaScore',l:'Malaysia\'s GIEI score in 2025/26. Twelve straight years at #1'},
    {layer:'giei',hl:['Indonesia','Malaysia'],title:'Indonesia versus Malaysia',body:'Indonesia has 236 million Muslims and the world\'s largest halal food market. Malaysia has 21 million and has topped the ecosystem ranking since the index began, leading in food, finance and pharmaceuticals. Eleven times the people; a fraction of the score. That gap is the whole story of this market.',stat:'indonesiaVsMalaysia',l:'more Muslims in Indonesia than Malaysia',acts:[{label:'Compare these two',act:'compare',args:['Indonesia','Malaysia']}]},
    {layer:'pop',hl:['Brazil','India','Russia','United States of America','Turkey'],title:'Much of the halal food is produced elsewhere',body:'OIC member countries imported $421.5 billion of halal-related goods in 2024. The largest suppliers into those markets are Brazil, India, Russia, Türkiye and the United States. Brazil, with a Muslim population in the low hundreds of thousands, is the biggest halal meat exporter on earth.',stat:'oicImports2024',l:'OIC halal-related imports, 2024. Heading to $608B by 2028',acts:[{label:'See the trade section',act:'section',args:['trade']}]},
    {layer:'fin',hl:['Saudi Arabia','Iran','Malaysia'],title:'And the money is concentrated in three places',body:'Islamic finance holds a further $5.99 trillion in assets, growing around 10% a year. Saudi Arabia, Iran and Malaysia hold about two-thirds of it between them; ten countries hold about 95%. Three-quarters is still banking, but sukuk issuance rose 25.6% in 2024.',stat:'financeConcentration',l:'of Islamic finance assets in Saudi Arabia, Iran and Malaysia',acts:[{label:'Break down the $6T',act:'section',args:['finance']}]},
    {layer:'giei',hl:['Pakistan','Senegal','United Kingdom'],title:'The map is changing',body:'Pakistan entered the ecosystem top ten for the first time. Senegal climbed 18 places to 25th. The United Kingdom sits at 14th, the highest-ranked non-Muslim-majority country and the West\'s main hub for Islamic finance. National strategy, not population, is what moves these rankings.',stat:'senegalRise',l:'places Senegal rose in a single year'},
    {layer:'pop',hl:null,title:'What this means depends on who you are',body:'For an investor, the gap between demand and infrastructure is an opportunity. For a policymaker, it is import dependence. For a business, it is a question of which market to enter first. Pick a perspective and the dashboard will reframe every chart for you.',n:'',l:'',cta:true}
  ]},
  hajj:{kicker:'A second story, in seven steps',title:'Two million people, one week, one city.',body:'The pilgrimage economy is the most concentrated consumer event on earth. Every year the Hajj compresses travel, food, insurance and finance for millions of people into a few days in Makkah. The chart follows the numbers.',graphic:'chart',steps:[
    {upto:2012,hl:[],title:'The peak before the rebuild',body:'In 2012 more than three million pilgrims performed Hajj. The following year Saudi Arabia cut country quotas by around 20% to allow the Grand Mosque to be expanded, and numbers settled near two and a half million.',stat:'hajj2012',l:'pilgrims in 2012, the largest Hajj on record'},
    {upto:2019,title:'A steady two and a half million',body:'By 2019, 2.49 million pilgrims attended, over 85% of them from abroad. Asian countries, led by Indonesia and Pakistan, supplied the majority. That is the scale the travel sector was built to serve.',stat:'hajj2019',l:'pilgrims in 2019, before the pandemic'},
    {upto:2021,title:'Then almost nobody',body:'In 2020 only around 10,000 residents were permitted to perform Hajj. In 2021 about 58,000. For two years the pilgrimage economy — hotels, airlines, tour operators, food supply — effectively closed.',stat:'hajj2020',l:'pilgrims in 2020, down 99.6% on 2019'},
    {upto:2023,title:'The rebound',body:'2022 was capped at one million and brought 926,000. In 2023 the cap came off and 1.84 million people came — the largest gathering since the pandemic and a signal to the whole travel sector that demand had not gone anywhere.',stat:'hajj2023',l:'pilgrims in 2023'},
    {upto:2026,title:'Settling below the old peak',body:'2024 brought 1.83 million; 2025, 1.67 million; 2026, 1.71 million. The numbers are stable but well below 2019, as the authorities manage heat, crowding and infrastructure works. Umrah, the year-round lesser pilgrimage, now brings around 17 million visitors a year on top.',stat:'hajj2026',l:'pilgrims in 2026 (GASTAT)'},
    {upto:2026,title:'Why this matters beyond Makkah',body:'Muslim-friendly travel is the fastest-growing sector in the halal economy — $249 billion in 2024, forecast at $424 billion by 2029, an 11.2% annual pace. Pilgrimage is the anchor demand around which airlines, hotel groups, fintechs and insurers build products for the rest of the year.',stat:'travelGrowth',l:'annual growth in Muslim-friendly travel to 2029',acts:[{label:'See all six sectors',act:'section',args:['sectors']}]},
    {upto:2026,title:'From pilgrimage to platform',body:'Saudi Arabia\'s Vision 2030 targets 30 million Umrah visitors a year. Digital pilgrimage platforms, sovereign travel apps and takaful travel cover are among the opportunity signals in the 2025/26 report. The pilgrimage is the oldest halal market and increasingly the most digitised one.',stat:'umrahTarget',l:'Umrah visitors a year targeted by 2030',cta:true}
  ]}
};
